/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWhatiswebmaintenanceRouteImport } from './routes/services/whatiswebmaintenance'
import { Route as ServicesWhatiswebdevelopmentRouteImport } from './routes/services/whatiswebdevelopment'
import { Route as ServicesWhatiswebdesignRouteImport } from './routes/services/whatiswebdesign'
import { Route as ServicesWebsitemaintenanceRouteImport } from './routes/services/websitemaintenance'
import { Route as ServicesWebdevelopmentRouteImport } from './routes/services/webdevelopment'
import { Route as ServicesWebdesignRouteImport } from './routes/services/webdesign'
import { Route as ServicesUiuxdesignRouteImport } from './routes/services/uiuxdesign'
import { Route as ServicesSeooptimizationRouteImport } from './routes/services/seooptimization'
import { Route as ServicesImportanceofwebmaintenanceRouteImport } from './routes/services/importanceofwebmaintenance'
import { Route as ServicesImportanceofwebdevelopmentRouteImport } from './routes/services/importanceofwebdevelopment'
import { Route as ServicesImportanceofwebdesignRouteImport } from './routes/services/importanceofwebdesign'
import { Route as ServicesEcommercesolutionsRouteImport } from './routes/services/ecommercesolutions'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWhatiswebmaintenanceRoute =
  ServicesWhatiswebmaintenanceRouteImport.update({
    id: '/whatiswebmaintenance',
    path: '/whatiswebmaintenance',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesWhatiswebdevelopmentRoute =
  ServicesWhatiswebdevelopmentRouteImport.update({
    id: '/whatiswebdevelopment',
    path: '/whatiswebdevelopment',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesWhatiswebdesignRoute = ServicesWhatiswebdesignRouteImport.update({
  id: '/whatiswebdesign',
  path: '/whatiswebdesign',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebsitemaintenanceRoute =
  ServicesWebsitemaintenanceRouteImport.update({
    id: '/websitemaintenance',
    path: '/websitemaintenance',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesWebdevelopmentRoute = ServicesWebdevelopmentRouteImport.update({
  id: '/webdevelopment',
  path: '/webdevelopment',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebdesignRoute = ServicesWebdesignRouteImport.update({
  id: '/webdesign',
  path: '/webdesign',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUiuxdesignRoute = ServicesUiuxdesignRouteImport.update({
  id: '/uiuxdesign',
  path: '/uiuxdesign',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeooptimizationRoute = ServicesSeooptimizationRouteImport.update({
  id: '/seooptimization',
  path: '/seooptimization',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesImportanceofwebmaintenanceRoute =
  ServicesImportanceofwebmaintenanceRouteImport.update({
    id: '/importanceofwebmaintenance',
    path: '/importanceofwebmaintenance',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesImportanceofwebdevelopmentRoute =
  ServicesImportanceofwebdevelopmentRouteImport.update({
    id: '/importanceofwebdevelopment',
    path: '/importanceofwebdevelopment',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesImportanceofwebdesignRoute =
  ServicesImportanceofwebdesignRouteImport.update({
    id: '/importanceofwebdesign',
    path: '/importanceofwebdesign',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesEcommercesolutionsRoute =
  ServicesEcommercesolutionsRouteImport.update({
    id: '/ecommercesolutions',
    path: '/ecommercesolutions',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/stack': typeof StackRoute
  '/services/ecommercesolutions': typeof ServicesEcommercesolutionsRoute
  '/services/importanceofwebdesign': typeof ServicesImportanceofwebdesignRoute
  '/services/importanceofwebdevelopment': typeof ServicesImportanceofwebdevelopmentRoute
  '/services/importanceofwebmaintenance': typeof ServicesImportanceofwebmaintenanceRoute
  '/services/seooptimization': typeof ServicesSeooptimizationRoute
  '/services/uiuxdesign': typeof ServicesUiuxdesignRoute
  '/services/webdesign': typeof ServicesWebdesignRoute
  '/services/webdevelopment': typeof ServicesWebdevelopmentRoute
  '/services/websitemaintenance': typeof ServicesWebsitemaintenanceRoute
  '/services/whatiswebdesign': typeof ServicesWhatiswebdesignRoute
  '/services/whatiswebdevelopment': typeof ServicesWhatiswebdevelopmentRoute
  '/services/whatiswebmaintenance': typeof ServicesWhatiswebmaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/stack': typeof StackRoute
  '/services/ecommercesolutions': typeof ServicesEcommercesolutionsRoute
  '/services/importanceofwebdesign': typeof ServicesImportanceofwebdesignRoute
  '/services/importanceofwebdevelopment': typeof ServicesImportanceofwebdevelopmentRoute
  '/services/importanceofwebmaintenance': typeof ServicesImportanceofwebmaintenanceRoute
  '/services/seooptimization': typeof ServicesSeooptimizationRoute
  '/services/uiuxdesign': typeof ServicesUiuxdesignRoute
  '/services/webdesign': typeof ServicesWebdesignRoute
  '/services/webdevelopment': typeof ServicesWebdevelopmentRoute
  '/services/websitemaintenance': typeof ServicesWebsitemaintenanceRoute
  '/services/whatiswebdesign': typeof ServicesWhatiswebdesignRoute
  '/services/whatiswebdevelopment': typeof ServicesWhatiswebdevelopmentRoute
  '/services/whatiswebmaintenance': typeof ServicesWhatiswebmaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/stack': typeof StackRoute
  '/services/ecommercesolutions': typeof ServicesEcommercesolutionsRoute
  '/services/importanceofwebdesign': typeof ServicesImportanceofwebdesignRoute
  '/services/importanceofwebdevelopment': typeof ServicesImportanceofwebdevelopmentRoute
  '/services/importanceofwebmaintenance': typeof ServicesImportanceofwebmaintenanceRoute
  '/services/seooptimization': typeof ServicesSeooptimizationRoute
  '/services/uiuxdesign': typeof ServicesUiuxdesignRoute
  '/services/webdesign': typeof ServicesWebdesignRoute
  '/services/webdevelopment': typeof ServicesWebdevelopmentRoute
  '/services/websitemaintenance': typeof ServicesWebsitemaintenanceRoute
  '/services/whatiswebdesign': typeof ServicesWhatiswebdesignRoute
  '/services/whatiswebdevelopment': typeof ServicesWhatiswebdevelopmentRoute
  '/services/whatiswebmaintenance': typeof ServicesWhatiswebmaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/services'
    | '/stack'
    | '/services/ecommercesolutions'
    | '/services/importanceofwebdesign'
    | '/services/importanceofwebdevelopment'
    | '/services/importanceofwebmaintenance'
    | '/services/seooptimization'
    | '/services/uiuxdesign'
    | '/services/webdesign'
    | '/services/webdevelopment'
    | '/services/websitemaintenance'
    | '/services/whatiswebdesign'
    | '/services/whatiswebdevelopment'
    | '/services/whatiswebmaintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/services'
    | '/stack'
    | '/services/ecommercesolutions'
    | '/services/importanceofwebdesign'
    | '/services/importanceofwebdevelopment'
    | '/services/importanceofwebmaintenance'
    | '/services/seooptimization'
    | '/services/uiuxdesign'
    | '/services/webdesign'
    | '/services/webdevelopment'
    | '/services/websitemaintenance'
    | '/services/whatiswebdesign'
    | '/services/whatiswebdevelopment'
    | '/services/whatiswebmaintenance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/services'
    | '/stack'
    | '/services/ecommercesolutions'
    | '/services/importanceofwebdesign'
    | '/services/importanceofwebdevelopment'
    | '/services/importanceofwebmaintenance'
    | '/services/seooptimization'
    | '/services/uiuxdesign'
    | '/services/webdesign'
    | '/services/webdevelopment'
    | '/services/websitemaintenance'
    | '/services/whatiswebdesign'
    | '/services/whatiswebdevelopment'
    | '/services/whatiswebmaintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/whatiswebmaintenance': {
      id: '/services/whatiswebmaintenance'
      path: '/whatiswebmaintenance'
      fullPath: '/services/whatiswebmaintenance'
      preLoaderRoute: typeof ServicesWhatiswebmaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/whatiswebdevelopment': {
      id: '/services/whatiswebdevelopment'
      path: '/whatiswebdevelopment'
      fullPath: '/services/whatiswebdevelopment'
      preLoaderRoute: typeof ServicesWhatiswebdevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/whatiswebdesign': {
      id: '/services/whatiswebdesign'
      path: '/whatiswebdesign'
      fullPath: '/services/whatiswebdesign'
      preLoaderRoute: typeof ServicesWhatiswebdesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/websitemaintenance': {
      id: '/services/websitemaintenance'
      path: '/websitemaintenance'
      fullPath: '/services/websitemaintenance'
      preLoaderRoute: typeof ServicesWebsitemaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/webdevelopment': {
      id: '/services/webdevelopment'
      path: '/webdevelopment'
      fullPath: '/services/webdevelopment'
      preLoaderRoute: typeof ServicesWebdevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/webdesign': {
      id: '/services/webdesign'
      path: '/webdesign'
      fullPath: '/services/webdesign'
      preLoaderRoute: typeof ServicesWebdesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/uiuxdesign': {
      id: '/services/uiuxdesign'
      path: '/uiuxdesign'
      fullPath: '/services/uiuxdesign'
      preLoaderRoute: typeof ServicesUiuxdesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seooptimization': {
      id: '/services/seooptimization'
      path: '/seooptimization'
      fullPath: '/services/seooptimization'
      preLoaderRoute: typeof ServicesSeooptimizationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/importanceofwebmaintenance': {
      id: '/services/importanceofwebmaintenance'
      path: '/importanceofwebmaintenance'
      fullPath: '/services/importanceofwebmaintenance'
      preLoaderRoute: typeof ServicesImportanceofwebmaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/importanceofwebdevelopment': {
      id: '/services/importanceofwebdevelopment'
      path: '/importanceofwebdevelopment'
      fullPath: '/services/importanceofwebdevelopment'
      preLoaderRoute: typeof ServicesImportanceofwebdevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/importanceofwebdesign': {
      id: '/services/importanceofwebdesign'
      path: '/importanceofwebdesign'
      fullPath: '/services/importanceofwebdesign'
      preLoaderRoute: typeof ServicesImportanceofwebdesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ecommercesolutions': {
      id: '/services/ecommercesolutions'
      path: '/ecommercesolutions'
      fullPath: '/services/ecommercesolutions'
      preLoaderRoute: typeof ServicesEcommercesolutionsRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesEcommercesolutionsRoute: typeof ServicesEcommercesolutionsRoute
  ServicesImportanceofwebdesignRoute: typeof ServicesImportanceofwebdesignRoute
  ServicesImportanceofwebdevelopmentRoute: typeof ServicesImportanceofwebdevelopmentRoute
  ServicesImportanceofwebmaintenanceRoute: typeof ServicesImportanceofwebmaintenanceRoute
  ServicesSeooptimizationRoute: typeof ServicesSeooptimizationRoute
  ServicesUiuxdesignRoute: typeof ServicesUiuxdesignRoute
  ServicesWebdesignRoute: typeof ServicesWebdesignRoute
  ServicesWebdevelopmentRoute: typeof ServicesWebdevelopmentRoute
  ServicesWebsitemaintenanceRoute: typeof ServicesWebsitemaintenanceRoute
  ServicesWhatiswebdesignRoute: typeof ServicesWhatiswebdesignRoute
  ServicesWhatiswebdevelopmentRoute: typeof ServicesWhatiswebdevelopmentRoute
  ServicesWhatiswebmaintenanceRoute: typeof ServicesWhatiswebmaintenanceRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesEcommercesolutionsRoute: ServicesEcommercesolutionsRoute,
  ServicesImportanceofwebdesignRoute: ServicesImportanceofwebdesignRoute,
  ServicesImportanceofwebdevelopmentRoute:
    ServicesImportanceofwebdevelopmentRoute,
  ServicesImportanceofwebmaintenanceRoute:
    ServicesImportanceofwebmaintenanceRoute,
  ServicesSeooptimizationRoute: ServicesSeooptimizationRoute,
  ServicesUiuxdesignRoute: ServicesUiuxdesignRoute,
  ServicesWebdesignRoute: ServicesWebdesignRoute,
  ServicesWebdevelopmentRoute: ServicesWebdevelopmentRoute,
  ServicesWebsitemaintenanceRoute: ServicesWebsitemaintenanceRoute,
  ServicesWhatiswebdesignRoute: ServicesWhatiswebdesignRoute,
  ServicesWhatiswebdevelopmentRoute: ServicesWhatiswebdevelopmentRoute,
  ServicesWhatiswebmaintenanceRoute: ServicesWhatiswebmaintenanceRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
