/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesUiuxdesignRouteImport } from './routes/services/uiuxdesign'
import { Route as ServicesSeooptimizationRouteImport } from './routes/services/seooptimization'
import { Route as ServicesEcommercesolutionsRouteImport } from './routes/services/ecommercesolutions'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUiuxdesignRoute = ServicesUiuxdesignRouteImport.update({
  id: '/uiuxdesign',
  path: '/uiuxdesign',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeooptimizationRoute = ServicesSeooptimizationRouteImport.update({
  id: '/seooptimization',
  path: '/seooptimization',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEcommercesolutionsRoute =
  ServicesEcommercesolutionsRouteImport.update({
    id: '/ecommercesolutions',
    path: '/ecommercesolutions',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/stack': typeof StackRoute
  '/services/ecommercesolutions': typeof ServicesEcommercesolutionsRoute
  '/services/seooptimization': typeof ServicesSeooptimizationRoute
  '/services/uiuxdesign': typeof ServicesUiuxdesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/stack': typeof StackRoute
  '/services/ecommercesolutions': typeof ServicesEcommercesolutionsRoute
  '/services/seooptimization': typeof ServicesSeooptimizationRoute
  '/services/uiuxdesign': typeof ServicesUiuxdesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/stack': typeof StackRoute
  '/services/ecommercesolutions': typeof ServicesEcommercesolutionsRoute
  '/services/seooptimization': typeof ServicesSeooptimizationRoute
  '/services/uiuxdesign': typeof ServicesUiuxdesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/services'
    | '/stack'
    | '/services/ecommercesolutions'
    | '/services/seooptimization'
    | '/services/uiuxdesign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/services'
    | '/stack'
    | '/services/ecommercesolutions'
    | '/services/seooptimization'
    | '/services/uiuxdesign'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/services'
    | '/stack'
    | '/services/ecommercesolutions'
    | '/services/seooptimization'
    | '/services/uiuxdesign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/uiuxdesign': {
      id: '/services/uiuxdesign'
      path: '/uiuxdesign'
      fullPath: '/services/uiuxdesign'
      preLoaderRoute: typeof ServicesUiuxdesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seooptimization': {
      id: '/services/seooptimization'
      path: '/seooptimization'
      fullPath: '/services/seooptimization'
      preLoaderRoute: typeof ServicesSeooptimizationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ecommercesolutions': {
      id: '/services/ecommercesolutions'
      path: '/ecommercesolutions'
      fullPath: '/services/ecommercesolutions'
      preLoaderRoute: typeof ServicesEcommercesolutionsRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesEcommercesolutionsRoute: typeof ServicesEcommercesolutionsRoute
  ServicesSeooptimizationRoute: typeof ServicesSeooptimizationRoute
  ServicesUiuxdesignRoute: typeof ServicesUiuxdesignRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesEcommercesolutionsRoute: ServicesEcommercesolutionsRoute,
  ServicesSeooptimizationRoute: ServicesSeooptimizationRoute,
  ServicesUiuxdesignRoute: ServicesUiuxdesignRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
